on:
  push:
    tags:
      - '*'
name: Test Create Github Release
jobs:
  create_release_notes:
    runs-on: ubuntu-latest
    name: Update Release Notes via GREN
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Deploy
        uses: DonMahallem/conventional-gh-release@dist
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
